version: '3.7'

services:

  postgresql_test:
    image: postgres
    environment:
      - POSTGRES_DB=prophy_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql_test/data/
    ports:
      - "5433:5433"
    command: -p 5433

  web_test:
    build:
      context: .
      dockerfile: ./Dockerfile
    # to make server accessible from browser add "-h 0.0.0.0"
    command: bash -c "pytest"
    container_name: prophy_test
    volumes:
      - .:/prophy/
      - py_wheels:/root/.cache/pip/wheels
    depends_on:
      - postgresql_test
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: "1"
          memory: 768M
        reservations:
          memory: 512M



volumes:
  db:
    driver: local
  py_wheels:
    driver: local
